//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASTEK.Architecture.UI.MVC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASTEK.Architecture.UI.MVC.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Account_Student {
            get {
                return ResourceManager.GetString("Account_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string Account_Teacher {
            get {
                return ResourceManager.GetString("Account_Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string Footer_ReservedRight {
            get {
                return ResourceManager.GetString("Footer_ReservedRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become member.
        /// </summary>
        public static string Home_BecomeMember {
            get {
                return ResourceManager.GetString("Home_BecomeMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Did Van Gogh&apos;s Turbulent Mind Depict One of the Most Complex Concepts in Physics?.
        /// </summary>
        public static string Home_Index_HeroSubtitle {
            get {
                return ResourceManager.GetString("Home_Index_HeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulla  uno nova cesserunt est indigestaque.
        /// </summary>
        public static string Home_Index_HeroTitle {
            get {
                return ResourceManager.GetString("Home_Index_HeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons you may like.
        /// </summary>
        public static string Home_LessonsMayLike {
            get {
                return ResourceManager.GetString("Home_LessonsMayLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons you didn&apos;t finish.
        /// </summary>
        public static string Home_LessonsNotFinished {
            get {
                return ResourceManager.GetString("Home_LessonsNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently published.
        /// </summary>
        public static string Home_RecentLessons {
            get {
                return ResourceManager.GetString("Home_RecentLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string Login_OtherService {
            get {
                return ResourceManager.GetString("Login_OtherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your {0} account.
        /// </summary>
        public static string Login_ProviderTitle {
            get {
                return ResourceManager.GetString("Login_ProviderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just sign up.
        /// </summary>
        public static string Login_SignUp {
            get {
                return ResourceManager.GetString("Login_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string LoginPartial_Dashboard {
            get {
                return ResourceManager.GetString("LoginPartial_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string LoginPartial_Disconnect {
            get {
                return ResourceManager.GetString("LoginPartial_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New lesson.
        /// </summary>
        public static string LoginPartial_NewLesson {
            get {
                return ResourceManager.GetString("LoginPartial_NewLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string LoginPartial_SignIn {
            get {
                return ResourceManager.GetString("LoginPartial_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string LoginPartial_SignUp {
            get {
                return ResourceManager.GetString("LoginPartial_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update account.
        /// </summary>
        public static string LoginPartial_UpdateAccount {
            get {
                return ResourceManager.GetString("LoginPartial_UpdateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for lessons.
        /// </summary>
        public static string Navbar_Search {
            get {
                return ResourceManager.GetString("Navbar_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string Register_AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("Register_AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not registered yet?.
        /// </summary>
        public static string Register_NotHaveAccount {
            get {
                return ResourceManager.GetString("Register_NotHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are....
        /// </summary>
        public static string RegisterModal_YouAre {
            get {
                return ResourceManager.GetString("RegisterModal_YouAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studies.
        /// </summary>
        public static string Studies {
            get {
                return ResourceManager.GetString("Studies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string Title_Account_ConfirmationForgotPassword {
            get {
                return ResourceManager.GetString("Title_Account_ConfirmationForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string Title_Account_ConfirmEmail {
            get {
                return ResourceManager.GetString("Title_Account_ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string Title_Account_ConfirmReset {
            get {
                return ResourceManager.GetString("Title_Account_ConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type.
        /// </summary>
        public static string Title_Account_ExternalLoginAccountType {
            get {
                return ResourceManager.GetString("Title_Account_ExternalLoginAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Title_Account_ForgotPassword {
            get {
                return ResourceManager.GetString("Title_Account_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Title_Account_Login {
            get {
                return ResourceManager.GetString("Title_Account_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register student.
        /// </summary>
        public static string Title_Account_RegisterStudent {
            get {
                return ResourceManager.GetString("Title_Account_RegisterStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register teacher.
        /// </summary>
        public static string Title_Account_RegisterTeacher {
            get {
                return ResourceManager.GetString("Title_Account_RegisterTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Title_Account_ResetPassword {
            get {
                return ResourceManager.GetString("Title_Account_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile informations.
        /// </summary>
        public static string Title_Account_UpdateAccount {
            get {
                return ResourceManager.GetString("Title_Account_UpdateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard - Student.
        /// </summary>
        public static string Title_Dashboard_Student {
            get {
                return ResourceManager.GetString("Title_Dashboard_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard - Teacher.
        /// </summary>
        public static string Title_Dashboard_Teacher {
            get {
                return ResourceManager.GetString("Title_Dashboard_Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Title_Home_Index {
            get {
                return ResourceManager.GetString("Title_Home_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New lesson.
        /// </summary>
        public static string Title_Lesson_Add {
            get {
                return ResourceManager.GetString("Title_Lesson_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add chapters &amp; parts.
        /// </summary>
        public static string Title_Lesson_AddChapter {
            get {
                return ResourceManager.GetString("Title_Lesson_AddChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a thumbnail.
        /// </summary>
        public static string Title_Lesson_AddDetails {
            get {
                return ResourceManager.GetString("Title_Lesson_AddDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter {0}. {1}.
        /// </summary>
        public static string Title_Lesson_Chapter {
            get {
                return ResourceManager.GetString("Title_Lesson_Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part {0}. {1}.
        /// </summary>
        public static string Title_Lesson_Part {
            get {
                return ResourceManager.GetString("Title_Lesson_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string Title_Lesson_Search {
            get {
                return ResourceManager.GetString("Title_Lesson_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update lesson.
        /// </summary>
        public static string Title_Lesson_Update {
            get {
                return ResourceManager.GetString("Title_Lesson_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update content.
        /// </summary>
        public static string Title_Lesson_UpdateChapter {
            get {
                return ResourceManager.GetString("Title_Lesson_UpdateChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study - {0}.
        /// </summary>
        public static string Title_Study_Index {
            get {
                return ResourceManager.GetString("Title_Study_Index", resourceCulture);
            }
        }
    }
}
