//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASTEK.Architecture.ApplicationService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASTEK.Architecture.ApplicationService.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and the confirmation password don&apos;t match.
        /// </summary>
        public static string Application_PasswordMatch {
            get {
                return ResourceManager.GetString("Application_PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your address.
        /// </summary>
        public static string ApplicationValidation_AddressRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your birthday.
        /// </summary>
        public static string ApplicationValidation_BirthDayRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_BirthDayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment length cannot be empty or have more than 2000 characters.
        /// </summary>
        public static string ApplicationValidation_CommentLength {
            get {
                return ResourceManager.GetString("ApplicationValidation_CommentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password.
        /// </summary>
        public static string ApplicationValidation_ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content length cannot be empty or have more than 8000 characters.
        /// </summary>
        public static string ApplicationValidation_ContentLength {
            get {
                return ResourceManager.GetString("ApplicationValidation_ContentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the content.
        /// </summary>
        public static string ApplicationValidation_ContentRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_ContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your country.
        /// </summary>
        public static string ApplicationValidation_CountryRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description cannot contain more than 2000 characters.
        /// </summary>
        public static string ApplicationValidation_DescriptionLength {
            get {
                return ResourceManager.GetString("ApplicationValidation_DescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the description.
        /// </summary>
        public static string ApplicationValidation_DescriptionRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is not valid.
        /// </summary>
        public static string ApplicationValidation_EmailFormat {
            get {
                return ResourceManager.GetString("ApplicationValidation_EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your email address.
        /// </summary>
        public static string ApplicationValidation_EmailRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your first name.
        /// </summary>
        public static string ApplicationValidation_FirstNameRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your gender.
        /// </summary>
        public static string ApplicationValidation_GenderRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your name.
        /// </summary>
        public static string ApplicationValidation_NameRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password length must have at least 8 characters.
        /// </summary>
        public static string ApplicationValidation_PasswordLength {
            get {
                return ResourceManager.GetString("ApplicationValidation_PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your password.
        /// </summary>
        public static string ApplicationValidation_PasswordRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your postal code.
        /// </summary>
        public static string ApplicationValidation_PostalCodeRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_PostalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the study.
        /// </summary>
        public static string ApplicationValidation_StudyRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_StudyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target cannot contain more than 500 characters.
        /// </summary>
        public static string ApplicationValidation_TargetLength {
            get {
                return ResourceManager.GetString("ApplicationValidation_TargetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the targets.
        /// </summary>
        public static string ApplicationValidation_TargetRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_TargetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title cannot contain more than 500 characters.
        /// </summary>
        public static string ApplicationValidation_TitleLength {
            get {
                return ResourceManager.GetString("ApplicationValidation_TitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the title .
        /// </summary>
        public static string ApplicationValidation_TitleRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your town.
        /// </summary>
        public static string ApplicationValidation_TownRequired {
            get {
                return ResourceManager.GetString("ApplicationValidation_TownRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between {0} et {0}.
        /// </summary>
        public static string ApplicationValidation_ValueRange {
            get {
                return ResourceManager.GetString("ApplicationValidation_ValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Display_ConfirmPassword {
            get {
                return ResourceManager.GetString("Display_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Display_Remember {
            get {
                return ResourceManager.GetString("Display_Remember", resourceCulture);
            }
        }
    }
}
