//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASTEK.Architecture.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfrastructureStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfrastructureStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASTEK.Architecture.Infrastructure.InfrastructureStrings", typeof(InfrastructureStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be at least {0} to signup.
        /// </summary>
        public static string Age_Minimum {
            get {
                return ResourceManager.GetString("Age_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Display_Address {
            get {
                return ResourceManager.GetString("Display_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Display_BirthDay {
            get {
                return ResourceManager.GetString("Display_BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Display_Comment {
            get {
                return ResourceManager.GetString("Display_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Display_Content {
            get {
                return ResourceManager.GetString("Display_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Display_Country {
            get {
                return ResourceManager.GetString("Display_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Display_Description {
            get {
                return ResourceManager.GetString("Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Display_Duration {
            get {
                return ResourceManager.GetString("Display_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Display_Email {
            get {
                return ResourceManager.GetString("Display_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string Display_FirstName {
            get {
                return ResourceManager.GetString("Display_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Display_Gender {
            get {
                return ResourceManager.GetString("Display_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Display_Hour {
            get {
                return ResourceManager.GetString("Display_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Display_Level {
            get {
                return ResourceManager.GetString("Display_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Display_Minute {
            get {
                return ResourceManager.GetString("Display_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Display_Name {
            get {
                return ResourceManager.GetString("Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Display_Password {
            get {
                return ResourceManager.GetString("Display_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Display_PhoneNumber {
            get {
                return ResourceManager.GetString("Display_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostalCode.
        /// </summary>
        public static string Display_PostalCode {
            get {
                return ResourceManager.GetString("Display_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study.
        /// </summary>
        public static string Display_Study {
            get {
                return ResourceManager.GetString("Display_Study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets.
        /// </summary>
        public static string Display_Target {
            get {
                return ResourceManager.GetString("Display_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Display_Title {
            get {
                return ResourceManager.GetString("Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string Display_Town {
            get {
                return ResourceManager.GetString("Display_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string Display_University {
            get {
                return ResourceManager.GetString("Display_University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found.
        /// </summary>
        public static string NotFound_Account {
            get {
                return ResourceManager.GetString("NotFound_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter not found.
        /// </summary>
        public static string NotFound_Chapter {
            get {
                return ResourceManager.GetString("NotFound_Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson not found.
        /// </summary>
        public static string NotFound_Lesson {
            get {
                return ResourceManager.GetString("NotFound_Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part not found.
        /// </summary>
        public static string NotFound_Part {
            get {
                return ResourceManager.GetString("NotFound_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study not found.
        /// </summary>
        public static string NotFound_Study {
            get {
                return ResourceManager.GetString("NotFound_Study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot contain whitespaces and must contain at least:
        ///- a number
        ///- a lowercase character
        ///- an uppercase character
        ///.
        /// </summary>
        public static string Password_InvalidFormat {
            get {
                return ResourceManager.GetString("Password_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid {1}.
        /// </summary>
        public static string Property_InvalidFormat {
            get {
                return ResourceManager.GetString("Property_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot not be empty or whitespace.
        /// </summary>
        public static string Property_IsNotNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Property_IsNotNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} length cannot contain more than {1} characters.
        /// </summary>
        public static string Property_MaximumLength {
            get {
                return ResourceManager.GetString("Property_MaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} length must contain at least {1} characters.
        /// </summary>
        public static string Property_MinimumLength {
            get {
                return ResourceManager.GetString("Property_MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than Zero..
        /// </summary>
        public static string Property_MustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Property_MustBeGreaterThanZero", resourceCulture);
            }
        }
    }
}
